### PR TITLE
mapbox layers

### PR DESCRIPTION
**Pull request by Mahdis-z**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
The example with the title "base tiles from USGS" should actually have base tiles from the USGS like in the Python version.

The final "add lines" example can go (should be in the lines doc)

**Comment by nicolaskruchten** [comment]
Please rebase onto `source-design-merge` to get CI working :)

**Comment by Mahdis-z** [comment]
> Please rebase onto `source-design-merge` to get CI working :)
> 
Done

**Comment by nicolaskruchten** [comment]
OK, let's merge this one.

**Pull request merged**
