### PR TITLE
fixed first subplot table

### PR DESCRIPTION
**Pull request by Kully**
@cldougl 
not sure why but the first subplot of tables in https://plot.ly/python/table-subplots/ still had an incorrect layout vis a vis Jack's comment in `python-api` in Slack

I corrected the format now. Must have by accident deleted the code and used the incorrect format of that subplot before the old PR merged.

### CODE REVIEW

**Comment by cldougl** [comment]
just 2 things I noticed:
1. the headers in the first table
screen shot 2017-11-29 at 12 09 27 pm
2. the last table got messed up again (looks like the dataframe isn't getting referenced correctly)
screen shot 2017-11-29 at 12 09 06 pm

let me know if you need help w/ either of those! I think it might help to reduce the left margin as well

**Comment by cldougl** [comment]
the first table still has a few spacing issues (looks like the dates are getting cut off and some of the headers are still getting cut off)

these changes are a good improvement though so it's okay if you want to merge this and then make a new pr for the spacing of the first table 👍  💃

**Comment by Kully** [comment]
> these changes are a good improvement though so it's okay if you want to merge this and then make a new pr for the spacing of the first table 👍 💃

I'd rather tackle all issues in this one PR

**Comment by cldougl** [comment]
💃

**Pull request merged**
