### PR TITLE
styling python data-upload tutorial

### PR DESCRIPTION
**Pull request by Kully**

### CODE REVIEW

**Comment by Kully** [comment]
Issue: https://github.com/plotly/documentation/issues/516

@cldougl ready for review

**Comment by Kully** [comment]
@cldougl okay, everything should be good!

**Comment by cldougl** [comment]
@Kully you have to add a trailing slash to the permalink also it looks like you're using an old version of publisher in the ipython notebook publisher cell
should be: `! pip install git+https://github.com/plotly/publisher.git --upgrade`

**Comment by Kully** [comment]
> @Kully you have to add a trailing slash to the permalink also it looks like you're using an old version of publisher in the ipython notebook publisher cell
> should be: ! pip install git+https://github.com/plotly/publisher.git --upgrade

Okay. I _did_ notice that a few of the notebooks in the `tutorials` folder had strange looking publisher cells.

Will update now.

**Comment by Kully** [comment]
@cldougl ready for 💃 ?

**Pull request merged**
