### PR TITLE
Merge Layouts

### PR DESCRIPTION
**Pull request by jdamiba**
The purpose of this PR is to refactor the layouts folder in this repository so that all of the posts use either the langindex or the base layout.

For the Python posts, it is necessary to include the layouts `getstart` and `user-guide` since they are being pulled from another repository in CI which still refers to those layouts. This also involves changing a conditional in the python index posts. 

For the posts which are being transitioned from the `getstart-base` or `getstart` layout to the `base `layout it is necessary to change their name attribute to compensate for the fact that the `base` layout adds in <lang> to the end of the string.

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Is this ready for review or are you still looking at some stuff?

**Comment by jdamiba** [comment]
This PR is ready for review. As we discussed on Slack, I have edited the name attribute for several posts and made sure that the Python logo appears on the Python V3 index page.

**Comment by jdamiba** [comment]
I actually need to push one more commit to this branch- in the last edit to the sidebar include the title of the 404 page gets inserted into the sidebar. Fixing that, then this is ready.

**Comment by nicolaskruchten** [comment]
OK let's do this. 💃

**Pull request merged**
