### PR TITLE
Array OK

### PR DESCRIPTION
**Pull request by etpinard**
screenshots:

image

image

image

@chriddyp @cldougl

### CODE REVIEW

**Comment by chriddyp** [comment]
contribution of the month! 🏆

**Comment by chriddyp** [comment]
💃  from me

**Comment by chriddyp** [comment]
@cldougl @Kully or @bcdunbar - could you merge and deploy this one?

**Comment by Kully** [comment]
@cldougl @bcdunbar 
I've merged, can one of you `rake deploy`?

I'm having trouble deploying on my end - had to recopy the directory with no luck :(

**Pull request merged**
