### PR TITLE
Update/r v4 (WIP)

### PR DESCRIPTION
**Pull request by timelyportfolio**
This pull request designed to initiate discussion on converting docs for @cpsievert major `v4.0` release.  See https://github.com/ropensci/plotly/pull/628.

### CODE REVIEW

**Comment by timelyportfolio** [comment]
List of to-dos

- [ ] `subplot` with `group_by`
- [ ] all geo examples
- [ ] pie charts

**Comment by cpsievert** [comment]
@timelyportfolio could you provide an example of your last point?

Also, `subplot` + `group_by` won't be possible, change those examples to some version of this:

```r
elong <- tidyr::gather(economics, variable, value, -date)
elong$id <- as.integer(factor(elong$variable))
p <- plot_ly(elong, x = ~date, y = ~value, color = ~variable, yaxis = ~paste0("y", id))
subplot(p, nrows = 5, shareX = TRUE)
```

**Comment by timelyportfolio** [comment]
@cpsievert, there are a couple of references (that I tried to remove/change) to `plot_ly` returning a `data.frame` and how the pipeline works well with with the returned `data.frame`.  These should be changed to a `plotly` object, and the other changed to discuss how it can still be used in a pipeline.

**Comment by cpsievert** [comment]
oh, I see, yea, I'll help out with that later in the week

**Comment by cpsievert** [comment]
Here's the small multiple maps:

```r
library(plotly)
library(dplyr)
df <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/1962_2006_walmart_store_openings.csv')

# common map properties
g <- list(
  scope = 'usa', 
  showland = T, 
  landcolor = toRGB("gray90"), 
  showcountries = F, 
  subunitcolor = toRGB("white")
)

one_plot <- function(dat) {
  dat %>% 
    plot_ly() %>%
    add_trace(
      # setting the geo attribute is _crucial_ here
      lon = ~LON, lat = ~LAT, type = "scattergeo", geo = "geo",
      marker = list(color = toRGB("blue", 0.05))
    ) %>%
    add_trace(
      lon = -78, lat = 47, mode = 'text', text = ~YEAR, type = "scattergeo", geo = "geo"
    ) %>% layout(geo = g)
}

lapply(split(df, df$YEAR), one_plot) %>% 
  subplot(nrows = 9) %>% 
  layout(
    showlegend = FALSE,
    title = 'New Walmart Stores per year 1962-2006<br> Source: <a href="http://www.econ.umn.edu/~holmes/data/WalMart/index.html">University of Minnesota</a>',
    width = 1000,
    height = 900,
    hovermode = FALSE
  )

```

**Comment by cldougl** [comment]
moved to https://github.com/plotly/documentation/pull/541

**Pull request closed without merging**
