### PR TITLE
fixed header caps and updated tables

### PR DESCRIPTION
**Pull request by Kully**

### CODE REVIEW

**Comment by Kully** [comment]
Fixes Issue: https://github.com/plotly/documentation/issues/659#event-929947062
I also fixed the imports order in the first cell of notebook.

@cldougl ready for review

**Comment by cldougl** [comment]
looks good @Kully can you add the 'New to Plotly' cell as well as the figure factory change.

**Comment by Kully** [comment]
Ready to merge?

**Comment by cldougl** [comment]
💃 yep looks good

**Pull request merged**
