### PR TITLE
removing _old scss folder

### PR DESCRIPTION
**Pull request by jdamiba**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
So you're able to regenerate the CSS from the SCSS without errors? Nothing is importing `_old` ?

**Comment by nicolaskruchten** [comment]
💃 (if so)

**Comment by jdamiba** [comment]
@nicolas Yes, I ran `gulp build` to regenerate the scss. That command ran without error and I also have the same Percy diff.

**Comment by nicolaskruchten** [comment]
good to merge

**Pull request merged**
