### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by jdamiba**
closes https://github.com/plotly/documentation/issues/1225

### CODE REVIEW

**Comment by priyatharsan** [comment]
@jdamiba I took a quick look at the changes and it looks like only the first few cells has been run and there are some deprecation warnings and error in some cells. I can take over this issue if you are okay with that?

**Comment by jdamiba** [comment]
@priyatharsan Sure, no problem.

**Comment by priyatharsan** [comment]
great!

**Comment by priyatharsan** [comment]
moving to https://github.com/plotly/documentation/pull/1273

**Pull request closed without merging**
