### PR TITLE
indicator tutorial's cleanup

### PR DESCRIPTION
**Pull request by Mahdis-z**
closes https://github.com/plotly/documentation/issues/1477

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
let's remove the multi-gauge example, and please auto-format *all* the examples

**Comment by nicolaskruchten** [comment]
Please rebase onto `source-design-merge` to get CI working :)

**Comment by Mahdis-z** [comment]
> Please rebase onto `source-design-merge` to get CI working :)

done

**Comment by nicolaskruchten** [comment]
So these commits made it into this PR somehow: https://github.com/plotly/documentation/pull/1472

I'll close the current PR and review them over there.

**Pull request closed without merging**
