### PR TITLE
Create 2015-06-24-multiple-make-subplots

### PR DESCRIPTION
**Pull request by aneda**
@chriddyp

### CODE REVIEW

**Comment by aneda** [comment]
@chriddyp added subplots titles

**Comment by aneda** [comment]
@chriddyp which one do you think better for the first subplot title example?

This is the basic subplot only title added:
https://plot.ly/~neda/1057/i-3-subplots.png

https://plot.ly/~neda/5717/multiple-subplots-with-titles.png

**Comment by chriddyp** [comment]
@aneda - I like the second example better

**Comment by aneda** [comment]
@chriddyp make_subplots with titles has been added

**Pull request closed without merging**
