### PR TITLE
fix waterfall plotly_js example

### PR DESCRIPTION
**Pull request by Kully**
fixes https://github.com/plotly/documentation/issues/906

### CODE REVIEW

**Comment by Kully** [comment]
@cldougl ready for review

**Comment by cldougl** [comment]
@bcdunbar thanks for taking a look!
@Kully can you add this fix for https://plot.ly/javascript/text-and-annotations/#styling-and-formatting-annotations in this pr (and then re-add the `ReviewReady` tag?)

**Comment by cldougl** [comment]
💃 after conflicts are resolved

**Comment by cldougl** [comment]
ping @Kully this is ready to go after you resolves the conflicts. Lmk if you need any help with that!

**Pull request merged**
