### PR TITLE
Joyplot Doc

### PR DESCRIPTION
**Pull request by Kully**
for Issue: https://github.com/plotly/documentation/issues/1018

### CODE REVIEW

**Comment by Kully** [comment]
Not having luck with violin plots...I am going to try building from scratch. Could be a fun FF.

**Comment by nicolaskruchten** [comment]
what's not working with violin plots? Groups as 'y', orientation='h', make them half...

**Comment by nicolaskruchten** [comment]
image

**Comment by Kully** [comment]
> Groups as 'y', orientation='h', make them half...

I'm having trouble allowing them to overlap. `violingap` doesn't do the trick.

**Comment by nicolaskruchten** [comment]
Right, they won't overlap... We could just generalize violin to allow it, rather than wrap a whole subplot-based infrastructure onto it... @etpinard ?

**Comment by Kully** [comment]
> We could just generalize violin to allow it
I'd like to take a first stab at adding that feature if we decide to go that route

**Comment by Kully** [comment]
Continuing off @nicolaskruchten 's point, the violins will not be able to overlap because `violingap` is only allowed in the closed interval $[0, 1]$.

---
If we place violins at y=0, 0.2, and 0.6

newplot

Nudging the 0.6 violin very close to 0.2 (0.21), we get:

newplot 1

---

If we allowed negative numbers for `violingap`, then this would solve the problem.

CODE FOR EXAMPLE:
```javascript
var data = [
{
  type: 'violin',
  x: [0, 5, 7, 8],
  points: 'none',
  box: {
    visible: false
  },
  boxpoints: false,
  line: {
    color: 'black'
  },
  fillcolor: '#8dd3c7',
  opacity: 0.6,
  meanline: {
    visible: false
  },
  y0: 0
},
{
  type: 'violin',
  x: [0, 4, 7, 8],
  points: 'none',
  box: {
    visible: false
  },
  boxpoints: false,
  line: {
    color: 'black'
  },
  fillcolor: '#d3c78d',
  opacity: 0.6,
  meanline: {
    visible: false
  },
  y0: 0.2
},
{
  type: 'violin',
  x: [0, 4, 7, 8],
  points: 'none',
  box: {
    visible: false
  },
  boxpoints: false,
  line: {
    color: 'black'
  },
  fillcolor: '#c78dd3',
  opacity: 0.6,
  meanline: {
    visible: false
  },
  y0: 0.21
}
];

var layout = {
  title: "Basic Horizontal Violin Plot",
  xaxis: {
    zeroline: false
  },
  violingap: 0
};

Plotly.newPlot('graph', data, layout);
```

@etpinard  WDYT?

**Comment by Kully** [comment]
> Ok, and what's wrong again with something like

I should have made them half violins to demonstrate the point. In the example you shared, I want to take the top blue one for example and shift it down a few pixels so that its middle line is somewhere between 1 and 2, while leaving the rest looking the same.

**Comment by etpinard** [comment]
> or example and shift it down a few pixels so that its middle line is somewhere between 1 and 2, while leaving the rest looking the same.

tweaking the `y` coordinates should do the trick, no?

**Comment by Kully** [comment]
> tweaking the `y` coordinates should do the trick, no?

I swapped all the y values of orange violin at 2 to 1.8 and get this: https://codepen.io/plotly/pen/yRXjPe

Can you see how the violins are now all thinner and I was not able to just shove that one violin down by a certain number of pixels?

**Comment by etpinard** [comment]
Thanks for codePen @Kully !

Would something like https://codepen.io/etpinard/pen/yRogaq be ok?

If not, we could add a `width` attribute for violin (and box) traces that would essentially override the internal [`dPos`](https://github.com/plotly/plotly.js/blob/d34015066c8d339f041c9ac5ae68762a342d5d86/src/traces/box/cross_trace_calc.js#L103-L104) parameter. This new attribute would be similar to `width` in bar traces.

Allowing `violingap` and `violingroupgap` to be negative would _work_, as these attributes [affect the violins' width](https://github.com/plotly/plotly.js/blob/d34015066c8d339f041c9ac5ae68762a342d5d86/src/traces/violin/plot.js#L46), but I don't see how we can justify making a "gap" value negative. The "real" parameter we want to override here is the violin width, not the gaps between them.

**Comment by Kully** [comment]
> f not, we could add a `width` attribute for violin (and box) traces that would essentially override the internal [`dPos`](https://github.com/plotly/plotly.js/blob/d34015066c8d339f041c9ac5ae68762a342d5d86/src/traces/box/cross_trace_calc.js#L103-L104) parameter.

I like this idea.

**Comment by nicolaskruchten** [comment]
vote to close... will be covered in the v4 docs

**Pull request closed without merging**
