### PR TITLE
updated the offline-static-image-export doc

### PR DESCRIPTION
**Pull request by priyatharsan**
closes https://github.com/plotly/documentation/issues/1255

### CODE REVIEW

**Comment by priyatharsan** [comment]
@michaelbabyn yeah I added additional `fig` example to compare how the plot would actually look like as in (`iplot``) and as image. But I have gone ahead and removed that `iplot(fig)` and simply referenced the previous `fig` to be exported as image. I was using `plotly.io.to_image` before tho.

**Comment by priyatharsan** [comment]
Let me know if this is good. Also, this pr fixes this issue too: https://github.com/plotly/documentation/issues/1230

**Comment by michaelbabyn** [comment]
Thanks for the changes @priyatharsan , if you could add `import plotly.io` at the top of the example then I would say :dancer: but it still might be nice to show `plotly.io.write_image` here as well since that is what most people use image export for.

**Comment by priyatharsan** [comment]
@michaelbabyn I've added info about `plotly.io.write_image` now. Let me know if its good.

**Comment by michaelbabyn** [comment]
Looks great @priyatharsan , :dancer:

**Pull request merged**
