### PR TITLE
Copy clipboard Box

### PR DESCRIPTION
**Pull request by Kully**
For Issue https://github.com/plotly/documentation/issues/856

### CODE REVIEW

**Comment by jdamiba** [comment]
I was able to successfully build this branch on my local machine and saw that the "Copy to clipboard!" is indeed in visible. However, on my machine the box is just text, and not clickable to add the text to my clipboard. Is that related to how the assets are loaded in a localhost environment vs production?

**Comment by Kully** [comment]
Report of the Issue so far:

Google (Chrome) has been moving away from flash over the years to the point that you need to allow flash to play on most websites.

The copyCode buttons rely on flash so this means that we need to allow each time, unless the button has a bigger resolution that 400X300 (not gonna happen).

If I do allow flash to run on the page, I am still hitting an error that I am working to fix now, but I am wondering if we should be moving away from flash altogether? I can't imagine anyone who would want to enable flash on Chrome before simply clicking a simple `Copy` button.

Thoughts?

**Comment by Kully** [comment]
relevant issue: https://github.com/zeroclipboard/zeroclipboard/issues/589

**Comment by Kully** [comment]
clipboard-works

**Comment by Kully** [comment]
@cldougl ready for a review - clipboard works now.

NOTE: I've only tested in Chrome. I'll test in Safari as well to be very sure.

**Comment by cldougl** [comment]
@Kully can you use browserstack and test all browsers?

**Comment by Kully** [comment]
Testing browsers: (OS: Mojave)
- [X] Firefox
- [ ] Opera
- [ ] Chrome
- [ ] Safari
- [ ]

**Comment by nicolaskruchten** [comment]
@michaelbabyn can you see if this works/can be merged please? copy-to-clipboard right now in prod does NOT work in Chrome/OSX for me

**Comment by michaelbabyn** [comment]
This works for me in chrome and firefox although on Chrome it's not clear without opening dev tools that you need flash set up and enabled for the button to work.

**Pull request closed without merging**
