### PR TITLE
Replace Hero BG Image

### PR DESCRIPTION
**Pull request by jdamiba**
closes https://github.com/plotly/documentation/issues/1425
Screen Shot 2019-08-13 at 11 57 02 AM

### CODE REVIEW

**Comment by jdamiba** [comment]
@michaelbabyn When reviewing this PR, please take note of how the background extends extends the full width of the hero- this was an issue @nicolaskruchten highlighted in the previous PR. 

See https://github.com/plotly/documentation/pull/1428#issuecomment-517412155

**Comment by nicolaskruchten** [comment]
Please note the font in the mock for #1425 ... it's Asap rather than Open Sans :)

**Comment by jdamiba** [comment]
@nicolaskruchten I am confused by your comment, can you please be more specific? Please see the following gif of this PR in my development environment. 

The pretitle and subtitle are `Open Sans` while the `<h2>` title is `Asap`, as in the mock. To confirm that the title is `Asap` I toggle the font-family style in the Inspector several times which reverts the title to `Open Sans` and back to `Asap` quickly.

screencast

**Comment by nicolaskruchten** [comment]
Something is likely not loaded (the font itself?) because the font in the image above is not actually Asap. The lowercase `L`s in "Plotly" in particular, compared to the mock in https://github.com/plotly/documentation/issues/1425 and compared to the font reference at https://fonts.google.com/specimen/Asap.

**Comment by jdamiba** [comment]
Thanks for clarifying @nicolaskruchten. I added a commit to include the Asap Google Font in the `<head>` on the website. 

Screen Shot 2019-08-14 at 10 40 35 AM

@michaelbabyn This PR should be good to go now.

**Pull request merged**
