### PR TITLE
Colorway correction in reference docs

### PR DESCRIPTION
**Pull request by Kully**
Fixes https://github.com/plotly/documentation/issues/938

### CODE REVIEW

**Comment by cldougl** [comment]
@Kully will this get overwritten if we update `_data/plotschema.json` programatically (ie during deploy)? If so, do you think you could come up w/ a more permanent solution?

**Comment by Kully** [comment]
Now each deploy is correcting the format of colorway so that appears as a list of colors in the reference page. The solution is to add `\'`s around the brackets of the colorway list:

`"dflt": '["#1f77b4","#ff7f0e",...]'`

Right now, the script _only_ looks for a `dflt`that points to a 10-item list each which start with `#`

**Comment by Kully** [comment]
> can you resolve the conflicts on this branch

sure thing

**Comment by Kully** [comment]
@cldougl resolved conflicts

**Pull request closed without merging**
