### PR TITLE
corner github links to documentation page

### PR DESCRIPTION
**Pull request by Kully**
Resolves Issue: https://github.com/plotly/documentation/issues/805

### CODE REVIEW

**Comment by Kully** [comment]
@jackparmer ready for review

**Comment by jackparmer** [comment]
It would be nice if Jekyll had a way to link the actual documentation page and not the root folder for the language. I don't think anyone is going to navigate through our Jekyll folder to fix a type or add a new example.

**Comment by Kully** [comment]
> It would be nice if Jekyll had a way to link the actual documentation page and not the root folder for the language. I don't think anyone is going to navigate through our Jekyll folder to fix a type or add a new example.

Yes, I agree that would be best. I'll see if I can find a way to link them individually like that.

**Comment by Kully** [comment]
closing in favor of https://github.com/plotly/documentation/pull/1030

**Pull request closed without merging**
