### PR TITLE
use scatter and contour files from datasets

### PR DESCRIPTION
**Pull request by Kully**
fixes https://github.com/plotly/documentation/issues/954

### CODE REVIEW

**Comment by Kully** [comment]
@bcdunbar issue is solved - the missing JSON files are now on the web so they can be referenced and read

**Comment by bcdunbar** [comment]
@Kully thanks!

Looks like the plots may be private here.

**Comment by Kully** [comment]
> Looks like the plots may be private here.

> Looks like the plots may be private here.

The plots are not private, not live or checking with `jekyll serve`. The url links point to the right json files too. What are you noticing specifically that is private?

**Comment by Kully** [comment]
> Oh I meant when I open https://plot.ly/~jordanpeterson/1125.embed (and the other plots) I get a 404

Okay, I made this and other relevant plots public. Can you verify it's not private on your end?

**Comment by jdamiba** [comment]
I can verify that  https://plot.ly/~jordanpeterson/1125.embed is not private on my end. 💃

**Pull request merged**
