### PR TITLE
style annotation html escape

### PR DESCRIPTION
**Pull request by Kully**
https://github.com/plotly/documentation/issues/967#event-1775628706

Work In Progress
<i> needs to become `&lt; i &gt;`

### CODE REVIEW

**Comment by jdamiba** [comment]
Change looks good to me. 💃

**Comment by Kully** [comment]
> Change looks good to me. 💃

It's not ready yet.

**Comment by michaelbabyn** [comment]
@Kully , I think this issue would be fixed if we passed the example content through Jekyll's `xml_escape` filter. We can do that by changing [this line](https://github.com/plotly/documentation/blob/source-design-merge/_includes/auto_examples.html#L15) of code to `<pre><code class="{{page.language}}">{{ example.content | xml_escape }}</code></pre>`

Jekyll takes care of doing the escaping and I'm not aware of any examples where we use html within the code, what do you think?

**Comment by Kully** [comment]
> I'm not aware of any examples where we use html within the code

Isn't example from the issue one? :https://plot.ly/javascript/text-and-annotations/#styling-and-formatting-annotations

**Comment by michaelbabyn** [comment]
Sorry, I was unclear. In that case we have html in the codeblock but it isn't being escaped. The solution I'm proposing will escape all html in all code blocks so if we are using the html to style any code in these codeblocks it would be escaped by that solution. So when I said I'm not aware of any example when we use html, I meant I'm not aware of any example where escaping the html would lead to unintended consequences.

**Comment by Kully** [comment]
Okay, thank you for the clarification. I tried it and unfortunately it wasn't showing the change when I jekyll served it locally.

I may have done some tinkering with the actual HTML blob, moved <br>s inside of strings or whatnot, so I'll make sure all of that is in order.

**Pull request closed without merging**
