### PR TITLE
Add GitHub stars To Homepage

### PR DESCRIPTION
**Pull request by jdamiba**
screen shot 2018-10-09 at 4 20 58 pm

Part of https://github.com/plotly/plotly-next/issues/159

### CODE REVIEW

**Comment by jdamiba** [comment]
I would like to add some space between the stars and the name of the library, but I'm having trouble getting css styles to load.

**Comment by jdamiba** [comment]
screen shot 2018-10-10 at 9 47 50 am

I put the github stars into their own div and added a css class to `_home.scss` nested in the `category-wrap` class. This increased the space between between the name of the library and the github stars as desired but now the stars are in the bottom left of the div instead of the center. 

It seems that the styles in the github-stars CSS class are not being applied- the extra space is as a result of the markup.

**Comment by jdamiba** [comment]
screen shot 2018-10-10 at 12 48 40 pm
screen shot 2018-10-10 at 12 48 44 pm

**Comment by cldougl** [comment]
(fyi @nicolaskruchten the class issue got resolved if you're just following this thread via email )

**Comment by nicolaskruchten** [comment]
Poor Matlab and its dismal star score :)

**Pull request merged**
