### PR TITLE
Figure widget update

### PR DESCRIPTION
**Pull request by michaelbabyn**
This is the PR for updating the graphwidget documentation to plotly.py version 3's FigureWidget for [this issue](https://github.com/plotly/documentation/issues/991).

- [x] Interactive Data Analysis with ipywidgets
- [x] FigureWidget overview
- [x] Interact notebook
- [x] Create New Window with Jupyter Lab
- [x] Slider Widget with Plotly
- [x] Using Mouse Events with Plotly FigureWidget
- [x] Adding Zoom Effects
- [x] Hover Events
- [x] Click Events
- [ ] add thumbnail gifs

### CODE REVIEW

**Comment by Kully** [comment]
@michaelbabyn gonna have a look now

**Comment by Kully** [comment]
screen shot 2018-09-03 at 6 04 08 pm

You should combine this two code blocks and

**Comment by michaelbabyn** [comment]
@Kully , I'll go back through these and see what I can merge and I'll get rid of that superfluous output from updating the figureWidget but I think it makes sense to keep the updates separated to help demonstrate that each code block will instantly update the graph. See below for what I mean.

figurewidget-update

**Comment by Kully** [comment]
> See below for what I mean.

no, you're absolutely right. I was a little unclear in my first comment. The second picture was demonstrating a **Good** use of small code chunks to show the functionality of adding different trace types.

**Comment by Kully** [comment]
screen shot 2018-09-04 at 11 28 48 am

there should not be this much white space between the param and arg:
```
figure = go.Figure(
    data=data,
    layout=layout
)
```

**Comment by Kully** [comment]
# Jupyter Lab with FigureWidget

screen shot 2018-09-04 at 11 58 11 am

`you're` not `your`

**Comment by Kully** [comment]
# Interact Decorator

screen shot 2018-09-04 at 1 59 19 pm

You should put an empty chart in here

---

**Comment by Kully** [comment]
# Slider Widget

Important note for all docs. The structure of our imports are like this:
```
# import
import plotly ...
...
from plotly import ...

# non-plotly imports
import ...
```
See the [scatter plot doc](https://plot.ly/python/line-and-scatter/#simple-scatter-plot) for an example of this.

screen shot 2018-09-04 at 4 07 37 pm

---

screen shot 2018-09-04 at 4 33 29 pm

PEP-8 - same comment from previous section:
```
widgets.FloatRangeSlider(
    min=xmin,
    max=xmax,
    step=(xmax - xmin) / 1000.0,
    ...
)
```

**Comment by Kully** [comment]
#### DashShader Case Study

Combine these 3 cells together

screen shot 2018-09-04 at 4 37 50 pm

**Comment by Kully** [comment]
# Click Events

separate the imports as explained above

**Comment by Kully** [comment]
# Selection Events
- separate the imports here too
- add a brief description after the title about what the doc is doing.

# Car Exploration

The `Load cars dataset` should not be so big. It should be an header4 (4 #s in markdown):

`#### Load cars dataset`

and `Cars dataset exploration with plotly.py version 3.0` should not be an empty section like that as it shows up in the sidebar like a normal section.

screen shot 2018-09-04 at 5 10 00 pm

**Comment by michaelbabyn** [comment]
@Kully , I made the changes you mentioned in all but the "case study" docs (since those are just Jon's with GIFs to show off the widget and I think it makes sense to leave them as they are). So I think this should be good to merge. What do you think?

**Comment by Kully** [comment]
@michaelbabyn It looks like you did at least some of the grammar edits, but my comments about the headers in `Car Exploration` are still not addressed.

Send me a message if you are confused about what I am asking and I can clarify.

**Comment by michaelbabyn** [comment]
I think they can be merged ASAP, @Kully wasn't sure if we should keep one of Jon's docs in there as is since it is quite different stylistically from the rest of the docs but that's all that's blocking.

**Comment by jackparmer** [comment]
> ... wasn't sure if we should keep one of Jon's docs in there as is since it is quite different stylistically from the rest of the docs but that's all that's blocking.

Yeah, we shouldn't let that hold this up. Please merge & deploy today with either Jon's doc or a modified version that is more stylistically similar.

**Comment by cldougl** [comment]
@jackparmer I told michael to wait until this could be reviewed before merging. @michaelbabyn feel free to merge now and we can deal with the styling later

**Comment by jonmmease** [comment]
Has this been deployed yet?  I'm still seeing the old GraphWidget stuff in the "Custom Controls with JavaScript" section.

screen shot 2018-09-23 at 6 55 39 am

Thanks for all your work on this @michaelbabyn!

**Pull request merged**
