### PR TITLE
modebar buttons

### PR DESCRIPTION
**Pull request by Mahdis-z**

### CODE REVIEW

**Comment by Mahdis-z** [comment]
@jdamiba FYI

**Comment by archmoj** [comment]
@Mahdis-z 
Would you mind providing a description for the PR?
Thanks in advance.

**Comment by Mahdis-z** [comment]
> @Mahdis-z
> Would you mind providing a description for the PR?
> Thanks in advance.

Yeah, the purpose of this PR is to provide more info some for this tutorial: https://plot.ly/javascript/configuration-options to show how to add/remove, show/hide buttons in ModeBar as well as changing the behaviour of the buttons.

**Comment by jdamiba** [comment]
@Mahdis-z @archmoj I am closing this PR in favor of https://github.com/plotly/documentation/pull/1668 as these changes are very closely related. 

The work from this branch has been merged into that one.

**Pull request closed without merging**
